### ISSUE TITLE
Automatic publishing of extension-specific books, when possible

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#14]
should doc infra interact with extension `info.xml` files?

migrated from [to-do list](https://github.com/civicrm/civicrm-docs/tree/638e243c6f4eb06086199e3ea8b529541368f688#to-do).

**Comment by seanmadsen** [comment]
@michaelmcandrew I'm not quite sure what this means. Can you clarify?

**Comment by michaelmcandrew** [comment]
Hey there,

It's a vague one, I know. It's basically about ensuring that we are doing as much as we can to automate the publishing of extensions documentation. 

I think the info.xml file in extensions has a documentation tag (or if not, it probably should) and maybe civicrm-docs should interfact with that somehow??

I think that our translation infrastructure does something similar when extensions are published based on the info.xml file.

Might be that we don't need to do anything - here would be a good place to document what we are / are not doing, and why.

**Comment by nganivet** [comment]
Seems like this one is far-fetched. Extension documentation should be linked to in the extensions directory and eventually in-app, but I see no reason to link to any extension's documentation from the user manuals. Or am I missing something?

**Comment by michaelmcandrew** [comment]
@nganivet - one of the aims of the new documentation project is to provide a recommended process for creating extension documentation and a place to publish it. so docs.civicrm.org has the user, admin and dev guide, but also docs.civicrm.org/extensions/cividiscount, docs.civicrm.org/extensions/civivolunteer, etc. That infrastructure is pretty much there now - we just need people to start using it.

I did nudge a few people in that direction here: https://civicrm.org/blog/michael-mcandrew/a-new-home-for-our-documentation and reached out to a couple of mature extensions, but there hasn't been any take up as yet...

**Comment by nganivet** [comment]
Yes, does not surprise me, the extensions' documentation should probably 
be in Github with the extension, either in the README.md or in the wiki. 
Spreading it in multiple locations does not make sense unless there are 
significant benefits in doing so.

------ Original Message ------

**Comment by michaelmcandrew** [comment]
To clarify:

* Extension authors will write their documentation directly in the github repo.
* People would be free to consume it directly in github if they wanted to, but the readthedocs based UI on docs.civicrm.org provides a much nicer UI for reading documentation
* The wiki is deprecated for documentation.

i.e. we are not suggesting spreading it in multiple locations.

To put the lack of take up in perspective: we're only just getting round to putting developer docs into markdown so it's still early days.

**Comment by totten** [comment]
Personally... as a developer who often works on Github... big +1 for storing the docs from each extensions' git repo, although... by the same token... the aesthetic/usability benefits of `mkdocs` aren't a huge deal for me. But I see the argument for more user-oriented materials.

If I understand, this is basically trying to create a stronger norm for docs among extensions. You just create some Markdown files in the extension (`civix generate:docs`?) -- you don't need to signup separately or build separate processes to publish nicer-looking books.

Related: `civicrm.org` provides a feed listing the git repos of all registered extensions. There's even a script, [`fetch-universe`](https://github.com/civicrm/civicrm-buildkit/blob/master/bin/fetch-universe), which can create+update local copies for all of them.

**Comment by seanmadsen** [comment]
A couple examples of the current state of things that I've come across recently and feel demonstrate the need for greater structure/consistency around extension documentation. 

- **CiviVolunteer** has several pages of good documentation in the [wiki](https://wiki.civicrm.org/confluence/display/CRMDOC/CiviVolunteer) (but the wiki makes it hard to tell there is even more than one page there). Also a tad more documentation exists on the [extension page](https://civicrm.org/extensions/civivolunteer), which unfortunately makes no mention of the wiki pages. And some more documentation is on [GitHub](https://github.com/civicrm/org.civicrm.volunteer), which also does not mention the wiki pages.
- **CiviRules** has [external docs](http://redmine.civicoop.org/projects/civirules/wiki) which are deprecated with a pointer to the wiki as current. But its [docs on the wiki](https://wiki.civicrm.org/confluence/display/CRM/CiviRules+extension) are deprecated with a pointer to the external docs as current. Then, [a different part of the wiki](https://wiki.civicrm.org/confluence/display/CRMDOC/CiviRules+Cookbook) has more docs which, as it happens, live underneath the "Develop" page so need to be moved as part of the Dev Guide content migration. 

These are just a couple examples, and this is not to lay blame on these extension maintainers. If I were to write an extension today, I would be quite confused about where best to place its documentation. In fact, an edit I made earlier today added a section on [Documenting Your Extension](https://github.com/civicrm/civicrm-dev-docs/blob/c7c8f75d6507acd01b25044df9e5c6416d34fd8a/docs/documentation.md#documenting-your-extension) to the documentation page, with its only contents being "TODO". We need some clarity here

I very much support what Michael described above about keeping docs in the extension's git repo and then creating books based on that. I think it would go a long way towards improving the documentation ecosystem within the whole CiviCRM project! 

I'll also mention that up until very recently (when I started to learn more about development), I would have never thought to look inside a git repository for documentation. The extensions listed on civicrm.org rarely have links to extension-specific documentation. Yes, often they have links to the git repo, which helps people like Tim who know to look there, but lots of people (like me until recently) will overlook that. I think the extensions database on civicrm.org also needs to do more to improve this situation, which is a bit off-topic within this issue, but could be made easier if we began to standardize expectations around extensions docs (i.e. if they *should* be in the git repo, then civicrm.org can be smarter about presenting that info, and perhaps linking to a more polished viewing experience on docs.civicrm.org if published)

**Comment by seanmadsen** [comment]
I would like to close this issue and will do so in 7 days if I don't hear any comments. 

Here's my thinking: 

* *automatically* publishing extensions books (just based on things like `info.xml` and `README`), would be cool, but I think it would be more work that it'd be worth. 
* We have some extensions specific books now
* I created documentation for [how to document your extension](https://docs.civicrm.org/dev/en/latest/documentation/extensions/) which I think is sufficient to address the need for better extensions docs

I'm trying to whittle down the issue queue here and I *think* we can close this. If you want to keep this issue open I'd like to hear a proposal for a plan of how we can move it forward.

**Comment by michaelmcandrew** [comment]
i vote close and re-open when someone comes along with a plan.

**Comment by seanmadsen** [comment]
Sounds good. Closing for now.
