### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#15]
A CiviCRM theme for documentation with the following goals: 

* display the version branch version (e.g. in user guide, show "4.6" or "latest") 
* link to docs.civicrm.org documentation home page (to allow user to switch between books/versions/etc)
* link to civicrm.org home page
* colors/branding matching CiviCRM branding, to some degree (not aiming for 100% match here, but at least a little bit)
* more control over future theme-level features as needed

migrated from [to-do list](https://github.com/civicrm/civicrm-docs/tree/638e243c6f4eb06086199e3ea8b529541368f688#to-do).

**Comment by seanmadsen** [comment]
Note to self: this looks like the place to put the new theme in place, once created: 

https://github.com/civicrm/civicrm-docs/blob/master/src/AppBundle/Utils/Publisher.php#L103

**Comment by seanmadsen** [comment]
Evaluate existing themes to pick a good one to fork: 

* [readthedocs](https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/readthedocs) - good
* [mkdocs](https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/mkdocs) - not so good
* [Cinder](https://github.com/chrissimpkins/cinder) - ??
* [Material](https://github.com/squidfunk/mkdocs-material) - ??
* [Alabaster](https://github.com/iamale/mkdocs-alabaster) - ??
* [PSinder]](https://github.com/michaeltlombardi/mkdocs-psinder) - ??
* [Bootswatch](https://github.com/mkdocs/mkdocs-bootswatch) - ??
* [Bootstrap](https://github.com/mkdocs/mkdocs-bootstrap) - ??

**Comment by seanmadsen** [comment]
@michaelmcandrew @totten @ErichBSchulz @nganivet Can I get some feedback here? 

I've looked at the above themes that already exist for MkDocs and I find Material to be far and above better than the other themes. The readthedocs theme (which we currently use) is in 2nd place, by in my opinion, pretty far behind. 

**How do you feel about basing our custom theme on *Material*?**

Make sure to [look at the demo](http://squidfunk.github.io/mkdocs-material).

@michaelmcandrew you [said](https://github.com/civicrm/civicrm-dev-docs/issues/54#issuecomment-272809487) you looked at some other themes besides readthedocs. Did you look at Material?

Note the goals listed atop this issue for pursuing a custom theme. I envision forking Material and making pretty minimal changes. Material already gives us many features that people have already discussed such as:

* collapsible navigation, which we [want](https://github.com/civicrm/civicrm-dev-docs/issues/54)
* "edit on GitHub" link that actually works, which we [want](https://github.com/civicrm/civicrm-docs/issues/23)
* permalinks to headings of all levels, which was a [topic](https://github.com/civicrm/civicrm-dev-docs/issues/52#issuecomment-272225775) within the hooks storage discussion
* no [js hack](https://github.com/civicrm/civicrm-dev-docs/issues/21) needed to present menu position to user

**Comment by nganivet** [comment]
@seanmadsen impressive theme! The demo looks really professional. I have not seen the ability to switch to another version and export to pdf as the readthedocs theme does (![readthedocs](https://cloud.githubusercontent.com/assets/3435067/22413152/9cb83444-e672-11e6-97e2-77081c3aab79.png)). Both are a must for our documentation. Did I miss ssomething, or can we add this to the theme by copying/pasting from the other theme.

**Comment by michaelmcandrew** [comment]
Awesome @seanmadsen.  It is an impressive theme. Maybe the biggest +1 for me is the internal page nav on the right hand side by default (as opposed to being inserted in the left hand ala rtd), which I wanted to implement for our theme. It's similar to, for example http://getbootstrap.com/css/ and I like it.

I tried it on the user guide and I'd be tempted to switch even as a default as it makes the main nav much more navigable.

A couple of points.

- it looks like it can be customised via quite a few options. to ensure consistency, we should probably do that in the published script as you mentioned
- I don't think that the available colours include our color.
- I think that the CiviCRM UI is moving toward the material theme, which is nice. At some point, we can consider co-ordinating :)

>  I envision forking Material and making pretty minimal changes

We could always start with no changes :)

PS it wasn't available when I was looking through the themes last time otherwise I would have likely recommended it as the base theme

**Comment by seanmadsen** [comment]
@nganivet I've moved the discussion about version switching to #33

**Comment by seanmadsen** [comment]
Ok here's how I want to implement this custom theme

1. Use the Material as a starting point
1. Implement our customizations using [theme extension](http://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme) which means we **create new css and js files which get *added*** to the Material theme
    * a different approach would be to fork the theme, make changes, and periodically pull upstream features in. But after reading about theme extension, I think we can probably do everything we need just by using extension. 
1. Create a **separate repository** for our customizations at `https://github.com/civicrm/cividocsmaterial`
    * This will be a very small repo. Probably just `css` and `js` directories with a few files. 
1. Create issues within the theme repository to track the goals of theme customization
1. Install Material on www-prod with `sudo pip install mkdocs-material`
1. Force the `theme: material` setting in [`Publisher.php`](https://github.com/civicrm/civicrm-docs/blob/master/src/AppBundle/Utils/Publisher.php#L103) as well as `extra_css:` and `extra_javascript:` appropriately. 
    * This means **all books would use our customized version of Material** regardless of the theme setting within the book's `mkdocs.yml` file
1. Also, update `mkdocs.yml` within each book (only two so far) to set `theme: material`. This means that people who edit content locally:
    * will need to `pip install mkdocs-material` before they can `mkdocs serve`. (I would update our meta documentation to make this clear.)
    * will have a local preview experience that closely matches the published viewing experience
    * will *not* have our theme *customizations* in place locally when previewing (which I think is okay, given that the customizations will likely be minimal)

Does this plan sound okay to folks?

**Comment by colemanw** [comment]
Go for it :)

**Comment by nganivet** [comment]
I would just align with the (informal) naming conventions and maybe title the repo mkdocs-theme-ext or mkdocs-material-ext. Sound more homogeneous to civicrm-dev-docs, civicrm-drupal or apachesolr_civiAttachments (maybe the last one should be named apachesolr-civiAttachments ;-))

**Comment by totten** [comment]
> (seanmadsen) Ok here's how I want to implement this custom theme...

Sounds good!

> (michaelmcandrew) Maybe the biggest +1 for me is the internal page nav on the right hand side by default (as opposed to being inserted in the left hand ala rtd)

Another big +1 on this. IMHO addresses the single biggest issue with the default theme.

>> (seanmadsen) Create a separate repository for our customizations at https://github.com/civicrm/cividocsmaterial 
>
> (nganivet) I would just align with the (informal) naming conventions and maybe title the repo mkdocs-theme-ext or mkdocs-material-ext... 

Agree that having some dashes would be more conventional.

Most of the civicrm repos include `civicrm-` because it helps ensure that contributors' forks have useful names. (Ex: If Alice contributes to `civicrm/docs` and `fizzbuzzerp/docs`, then `alice/docs` becomes a conflicted name.) The names  `civicrm/civicrm-docs-material` or `civicrm/mkdocs-material-civicrm` would be better for avoiding conflicts.

**Comment by seanmadsen** [comment]
@michaelmcandrew can you do step 5 in my list above? Then I'd like to set `theme: material` within the Dev Guide `hooks-op-4` branch so that we can (1) make sure Material is working on www-prod and (2) see how the hooks option 4 migration looks within Material, like you were [wondering](https://github.com/civicrm/civicrm-dev-docs/issues/71#issuecomment-276051961).

**Comment by michaelmcandrew** [comment]
@seanmadsen number 5 now done (though without sudo for now). Let me know if that worked for you.

**Comment by seanmadsen** [comment]
Custom theme is up and running now! Closing.
