### ISSUE TITLE
Home page which gives list of all books in system

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#18]
The docs system should provide a welcoming home page at docs.civicrm.org which lists all the books defined in `app/config/books/`. 

migrated from [to-do list](https://github.com/civicrm/civicrm-docs/tree/638e243c6f4eb06086199e3ea8b529541368f688#to-do).

**Comment by michaelmcandrew** [comment]
FYI, this is already happening - it is just being hidden by a redirect. It does need a bit of fleshing out. Copying content from http://civicrm.org/documentation to https://github.com/civicrm/civicrm-docs/blob/master/src/AppBundle/Resources/views/Read/home.html.twig would do it.

**Comment by seanmadsen** [comment]
Great. I can see this home page with my local install now. Closing this issue, and will create others about improving the home page
