### ISSUE TITLE
Provide language and version switching capability within books

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#22]
The User Guide has multiple versions and multiple languages, all of which are listed on https://civicrm.org/documentation but many URLs for this guide point only to the latest English version at https://docs.civicrm.org/user/en/latest/. Once a reader arrives there, it is not apparent that they have the option to read the guide in other languages or for other versions.

**Comment by michaelmcandrew** [comment]
i don't think the other language versions are complete enough to be linked to just now. The https://docs.civicrm.org/ home page provides that facility. As soon as a stable version is created for a book in the books.yml file, it will show up there...

**Comment by seanmadsen** [comment]
This is pretty much a duplicate of #33 and thus will be addressed within [civicrm-docs-material#4](https://github.com/civicrm/civicrm-docs-material/issues/4)
