### ISSUE TITLE
Home page - improve visual style

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#27]
Would be great to get the branding on the docs home page to match that on civicrm.org. For example, putting the logo up there, and using the same font, colors, etc.

**Comment by michaelmcandrew** [comment]
The css is pulled direct from civicrm.org - see https://github.com/civicrm/civicrm-docs/blob/master/app/Resources/views/base.html.twig#L9 so fonts and colours should match already.

Just need to add the logo https://civicrm.org/sites/civicrm.org/themes/civicrm_bootstrap/logo.png and make appropriate use of bootstrap's layout tools.

**Comment by seanmadsen** [comment]
Done now. Closing
