### ISSUE TITLE
Home page - books missing

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#28]
In my local installation of civicrm-docs I see a home page which lists the User Guide but does not list the Dev Guide. When I publish all books via command line the Dev Guide is include in this publishing process, so the app is well aware of the existence of the Dev Guide. Tim also [observed](https://chat.civicrm.org/civicrm/pl/7fh9y7w5o7d458yukjsuf33mby) the same behavior.

**Comment by michaelmcandrew** [comment]
NOt a bug - only stable books are published: https://github.com/civicrm/civicrm-docs/blob/master/src/AppBundle/Controller/ReadController.php#L52
