### ISSUE TITLE
Create book categorization functionality

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#30]
I would like for civicrm-docs to be capable of hosting extension-specific books eventually. I can imagine a day when there are a handful of books core-related books (e.g. User, Admin, Dev), plus over a dozen extension-specific books. When this day comes, having a docs home page that separates core-related books from extension-specific books will make the home page easier to navigate. 

I propose the following is added to a book's `.yml` config file: 

```yaml
category: core
```

or 

```yaml
category: extension
```

If this setting is missing, then the app would assume "extension". 

After these categories are in place, the home page can be modified to display books separately by category. 

Why do this now, when there are zero extension-specific books? &mdash; I think that if we can get *one* extension-specific book in there and make the home page look really slick and well-organized, it will help motivate other extensions maintainers to set up their own docs in books.

**Comment by michaelmcandrew** [comment]
Sounds good.
