### ISSUE TITLE
Create book sorting functionality

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#31]
Currently the home page lists books alphabetically. I'd like to eventually show books in the following order: 

* User Guide
* Administrator Guide
* Developer Guide

I'm proposing adding a new configuration value to each book's `.yml` file as follows: 

```yaml
weight: 2
```

Then books could be assigned specific weights and ordered as such.

**Comment by michaelmcandrew** [comment]
Or use a yaml file ordering (and maybe grouping) - might be more consistent / intuitive. But yes, we need ordering.

**Comment by michaelmcandrew** [comment]
Also, I'm thinking we should keep extensions alphabetised for now.

If there are only three books that we want to have a specific order in their own section, we might be justified in hard coding that view logic in the template: https://github.com/civicrm/civicrm-docs/blob/master/src/AppBundle/Resources/views/Read/home.html.twig

**Comment by seanmadsen** [comment]
+1 for alphabetized extension books, even when core books are custom-sorted.

**Comment by seanmadsen** [comment]
@michaelmcandrew re: "Or use a yaml file ordering"

Keeping the ordering data within each book's `.yml` file feels a little cleaner to me. With a separate file for sorting, then we run the risk of a book being defined in it's own file but not the sorting file, or vice versa. And perhaps the only negative affect of this bad data right now would be that the books wouldn't be sorted correctly. But in the future, this data model could open the door for strange bugs, like if a developer thinks "oh, here is one file that lists all the books, *this* is the authoritative source of which books are 'in' the system". Granted, the "weights" approach definitely has the downside that it's more cumbersome to edit multiple file when re-ordering books, but I think this task will be rare, especially since we want extensions books listed alphabetically. Another downside to "weights" is the risk of a book not being sorted correctly if it has the same weight as another book, but this risk has a very low damage, and is easily fixed. I imagine we'd give the User Guide a weight of something like -100 so that it's basically always on top, even if other books are accidentally added without a weight value (and thus assumed to be 0). I'm pretty sure this is how the data model works for menu items in Drupal and CiviCRM. 

I don't feel super strongly about this, but just want to offer the opinion in an attempt at avoiding bugs in the future.
