### ISSUE TITLE
Force a standard set of markdown extensions to be enabled for all books

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#34]
There are some markdown extensions that we basically just want to be enabled all the time, even if each book's `mkdocs.yml` file doesn't enable them. I think we should force them to be enabled at [this point in the code](https://github.com/civicrm/civicrm-docs/blob/master/src/AppBundle/Utils/Publisher.php#L103). 

It should set the following: 

```yaml
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
```

More details within [Material's docs](http://squidfunk.github.io/mkdocs-material/extensions/pymdown/)

**Comment by seanmadsen** [comment]
I have been thinking more about this and come the the conclusion that it's a bad idea. We want content editors using `mkdocs serve` to have the most realistic preview possible, so I think the extensions settings do, in fact, belong within each book. I think the only thing that should be force-added by civicrm-docs is the theme customizations, and those should be minimal.

Closing.

**Comment by michaelmcandrew** [comment]
agreed, and I think that setting in the book repo is fine and should be encouraged even for the theme. We should just mention that we override certain settings on docs.civicrm.org.
