### ISSUE TITLE
remove docs:serve command

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#44]
Hey @totten I [see](https://github.com/civicrm/civicrm-docs/commit/5ea1844066be02463bc71042dd8521dcb2a8936c) that last year you added the `docs:serve` command. Do you use this command? I'm wondering if we can remove it. I've been doing a [whole bunch of refactoring](https://github.com/seanmadsen/civicrm-docs/commits/refactor-model) (so far just in my own fork) and when I came across `docs:serve` I said "hmm, this is a cool idea, but I'm not sure it's worth maintaining, given the ease of running `mkdocs serve`", so I [removed it](https://github.com/seanmadsen/civicrm-docs/commit/1e9da6a0e40e38ef3da4277ca85e183bec46eb31). It wouldn't be too hard for me to put it back, and update the code to conform to some of the changes in my refactor, but I wonder how you'd feel about dropping this functionality from civicrm-docs to keep the app's purpose more focused on publishing.

**Comment by totten** [comment]
@seanmadsen I think it's ok to remove. TBH, half the time I've done `mkdocs serve` too.
