### ISSUE TITLE
Implement "watchers" email addresses in book config files

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#54]
This feature was there before my refactor, but I didn't carry it through since none of the books were actually using it. 

The idea here is that in a book's yaml config file, one could specify a list of email addresses which should always be notified during the publishing process. This list should be specified at the "language" level for a book.

**Comment by michaelmcandrew** [comment]
Might not be necessary. Could always watch via github

**Comment by seanmadsen** [comment]
Oh good point. I like that better because people can turn it on/off without having to edit/PR the book config files. 

In light of this suggestion, I'm closing this issue.
