### ISSUE TITLE
Say "guides" instead of "books"

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#56]
Remove language about "books", and change it to "guides" instead. 

I think the home page is the only place where this change is needed within this repository. 

Convo originally started by @michaelmcandrew [here](https://chat.civicrm.org/civicrm/pl/ksz16ognw3dxim6s8mmixh69pe)

**Comment by seanmadsen** [comment]
Oh, also change it here too: https://github.com/civicrm/civicrm-docs/blob/master/README.md

**Comment by seanmadsen** [comment]
Related: https://github.com/civicrm/civicrm-dev-docs/issues/131

**Comment by xurizaemon** [comment]
I'm just proposing a reword actually - I think we can drop the use of a term in lots of places. PR in a moment.
