### ISSUE TITLE
switch from symfony/yaml to the php yaml extension for yaml processing

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-docs#8]
symfony/yaml doesn't support all yaml formatting (only a subset that is useful for configuration files).

switching to php's yaml extension should give us more robust support (and amongst other things) allow people to write yaml comments that start at the beginning of the line.

**Comment by michaelmcandrew** [comment]
But wil alienate people that can't install the php yaml extension, so maybe we shouldn't...

**Comment by ErichBSchulz** [comment]
I think keep it simple...

**Comment by seanmadsen** [comment]
Seems like we're doing okay without this change. Can we close this issue @michaelmcandrew?

**Comment by michaelmcandrew** [comment]
yeah, and [actually](https://github.com/civicrm/cv/pull/3#issuecomment-275823339), it might be better to stick with what we have.
